In [2]:
import torch

In [4]:
tensor = torch.randn(2,4,3)
tensor

tensor([[[ 0.1259,  0.9333,  1.3487],
         [-0.1114,  0.1357,  0.6399],
         [ 0.5633,  1.0138, -0.1472],
         [ 1.9984, -2.2520,  0.9717]],

        [[ 0.1680, -2.1899,  0.8044],
         [ 0.1984,  1.0795, -1.1988],
         [ 0.0077, -1.0938,  1.0544],
         [-0.1446, -1.0935, -0.0451]]])

In [6]:
tensor_permuted = torch.permute(tensor, (2, 0, 1))
tensor_permuted

tensor([[[ 0.1259, -0.1114,  0.5633,  1.9984],
         [ 0.1680,  0.1984,  0.0077, -0.1446]],

        [[ 0.9333,  0.1357,  1.0138, -2.2520],
         [-2.1899,  1.0795, -1.0938, -1.0935]],

        [[ 1.3487,  0.6399, -0.1472,  0.9717],
         [ 0.8044, -1.1988,  1.0544, -0.0451]]])

In [7]:
tensor[1, 1, 2], tensor_permuted[2,1,1]

(tensor(-1.1988), tensor(-1.1988))

In [11]:
tensor[:, :, 1], tensor_permuted[1, :, :]

(tensor([[ 0.9333,  0.1357,  1.0138, -2.2520],
         [-2.1899,  1.0795, -1.0938, -1.0935]]),
 tensor([[ 0.9333,  0.1357,  1.0138, -2.2520],
         [-2.1899,  1.0795, -1.0938, -1.0935]]))

In [12]:
tensor[:,:,0], tensor_permuted[0, :, :]

(tensor([[ 0.1259, -0.1114,  0.5633,  1.9984],
         [ 0.1680,  0.1984,  0.0077, -0.1446]]),
 tensor([[ 0.1259, -0.1114,  0.5633,  1.9984],
         [ 0.1680,  0.1984,  0.0077, -0.1446]]))

In [13]:
tensor[:,:,2], tensor_permuted[2, :, :]

(tensor([[ 1.3487,  0.6399, -0.1472,  0.9717],
         [ 0.8044, -1.1988,  1.0544, -0.0451]]),
 tensor([[ 1.3487,  0.6399, -0.1472,  0.9717],
         [ 0.8044, -1.1988,  1.0544, -0.0451]]))